[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 100
target-version = ['py37']

extend-exclude = '''
/(
  | git
  | examples
  | dist
)/
'''